require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/bundle
    - bin/rake
    - bin/rspec
    - bin/rubocop
    - vendor/**/* # fix for CI
  TargetRubyVersion: 2.5
  NewCops: enable

#################### Layout ##############################

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/LineEndStringConcatenationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

#################### Metrics ##############################

Metrics/ModuleLength:
  Exclude:
    - lib/auxiliary_rails/concerns/resourceable.rb

#################### Style ###############################

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Exclude:
    - lib/auxiliary_rails/view_helpers/human_name_helper.rb
    - lib/auxiliary_rails_resourceable/railtie.rb
